name: Automated Infrastructure and Application Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2

jobs:
  deploy:
    name: Deploy Complete Infrastructure and Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Deploy infrastructure and applications
        working-directory: terraform
        run: |
          terraform plan -out=tfplan
          terraform apply tfplan

      - name: Get deployment results
        working-directory: terraform
        run: |
          echo "Frontend URL: $(terraform output -raw frontend_url)"
          echo "Backend URL: $(terraform output -raw backend_url)"
